/**
 * Credit notes and issued-invoice integrity.
 *
 * A credit note IS an invoice record (`Invoice.kind = 'credit_note'`) stored in
 * the same store: it reuses the numbering (its own `AV-YYYY-0001` series with
 * the same gap-free floor), the template snapshot, the PDF renderer, the CSV
 * exporter and the backup format - no parallel document model exists. Amounts
 * are stored positive; every aggregate adds documents through `documentSign`,
 * so there is exactly one subtraction rule in the whole app.
 *
 * Issued (non-draft) documents are historical: the fields history depends on
 * are locked (`lockedFieldChanged`), and a correction is a new credit note -
 * never an edit of the original.
 */
import type { Invoice, InvoiceItem } from '../store/types'

/** Default prefix of the credit-note number series (French "avoir"). */
export const CREDIT_NOTE_FALLBACK_PREFIX = 'AV'

export function isCreditNote(invoice: Pick<Invoice, 'kind'>): boolean {
  return invoice.kind === 'credit_note'
}

/** +1 for an invoice, −1 for a credit note. */
export function documentSign(invoice: Pick<Invoice, 'kind'>): 1 | -1 {
  return isCreditNote(invoice) ? -1 : 1
}

/**
 * Fields of an issued (non-draft) document that history depends on. Status,
 * paidAt, due date, notes, payment method, project and display options stay
 * editable: they describe what happens to the document, not what it said.
 */
export const LOCKED_INVOICE_FIELDS = [
  'number', 'customerId', 'currency', 'items', 'subtotal', 'tax', 'total',
  'taxRate', 'issueDate', 'kind', 'creditsInvoiceId',
] as const

const itemEssence = (item: InvoiceItem) => {
  // Ids are regenerated by the form and the line total is derived from the other
  // fields (quantity × unit price less the discount), so neither is history: a form
  // that recomputes the total must not look like an edit of an issued document.
  const { id: _id, total: _total, ...rest } = item
  return rest
}

const itemsEquivalent = (a: InvoiceItem[], b: InvoiceItem[]) =>
  a.length === b.length && a.every((item, index) => JSON.stringify(itemEssence(item)) === JSON.stringify(itemEssence(b[index])))

/**
 * The first locked field a patch tries to change on an issued document, or
 * null when the patch is safe (drafts are always safe). Unchanged values in
 * the patch are fine, so a full-form save that only edits notes still works.
 */
export function lockedFieldChanged(current: Invoice, patch: Partial<Invoice>): string | null {
  if (current.status === 'draft') return null
  for (const field of LOCKED_INVOICE_FIELDS) {
    if (!(field in patch)) continue
    const next = (patch as unknown as Record<string, unknown>)[field]
    const value = (current as unknown as Record<string, unknown>)[field]
    if (field === 'items') {
      if (!itemsEquivalent(current.items, (next as InvoiceItem[]) || [])) return field
    } else if (field === 'taxRate') {
      // A missing rate and an explicit 0 mean the same document.
      if (Number(next || 0) !== Number(value || 0)) return field
    } else if (next !== value && !(next == null && value == null)) {
      return field
    }
  }
  return null
}

/**
 * Draft credit note covering the full amount of an invoice. The user adjusts
 * the lines while it is a draft; the original invoice is never touched.
 * Amounts stay positive - the sign lives in `documentSign` only.
 */
export function creditNoteFromInvoice(
  invoice: Invoice,
  number: string,
  issueDate: string,
): Omit<Invoice, 'id' | 'createdAt' | 'updatedAt'> {
  return {
    kind: 'credit_note',
    creditsInvoiceId: invoice.id,
    number,
    customerId: invoice.customerId,
    projectId: invoice.projectId,
    currency: invoice.currency,
    language: invoice.language,
    pdfColor: invoice.pdfColor,
    exchangeRate: invoice.exchangeRate,
    rateCurrency: invoice.rateCurrency,
    taxRate: invoice.taxRate,
    template: invoice.template ? structuredClone(invoice.template) : undefined,
    paymentMethod: invoice.paymentMethod,
    items: invoice.items.map(item => ({ ...item, id: crypto.randomUUID() })),
    subtotal: invoice.subtotal,
    tax: invoice.tax,
    total: invoice.total,
    status: 'draft',
    issueDate,
    dueDate: issueDate,
    notes: '',
  }
}
