import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { createRequire } from 'node:module'

/**
 * The Android modules cannot run here (no JDK, no SDK), so these checks read the
 * Gradle files the way Gradle would and were written after CI caught a real
 * regression: a rewrite of `android/app/build.gradle` that kept the versioning
 * but silently dropped the `dependencies { }` block and
 * `apply from: 'capacitor.build.gradle'`. The first build then failed with
 * "resource color/colorPrimary not found", because `:capacitor-android` is what
 * contributes that colour resource.
 */
const appGradle = readFileSync('android/app/build.gradle', 'utf8')
const variables = readFileSync('android/variables.gradle', 'utf8')
const require = createRequire(import.meta.url)

const dependencyBlock = (() => {
  const start = appGradle.indexOf('dependencies {')
  assert.ok(start >= 0, 'android/app/build.gradle must declare dependencies { }')
  return appGradle.slice(start, appGradle.indexOf('\n}', start))
})()

test('the app module keeps every dependency the Capacitor template needs', () => {
  for (const dependency of [
    "implementation fileTree(include: ['*.jar'], dir: 'libs')",
    'implementation "androidx.appcompat:appcompat:$androidxAppCompatVersion"',
    'implementation "androidx.coordinatorlayout:coordinatorlayout:$androidxCoordinatorLayoutVersion"',
    'implementation "androidx.core:core-splashscreen:$coreSplashScreenVersion"',
    "implementation project(':capacitor-android')",
    "implementation project(':capacitor-cordova-android-plugins')",
    'testImplementation "junit:junit:$junitVersion"',
    'androidTestImplementation "androidx.test.ext:junit:$androidxJunitVersion"',
    'androidTestImplementation "androidx.test.espresso:espresso-core:$androidxEspressoCoreVersion"',
  ]) {
    assert.ok(dependencyBlock.includes(dependency), `missing dependency: ${dependency}`)
  }
  // Without this the plugin modules generated by cap sync are never built.
  assert.ok(appGradle.includes("apply from: 'capacitor.build.gradle'"), "apply from: 'capacitor.build.gradle' is required")
  // The generated file is the one that lists the plugin projects.
  const generated = readFileSync('android/app/capacitor.build.gradle', 'utf8')
  for (const plugin of [...readFileSync('android/capacitor.settings.gradle', 'utf8').matchAll(/include ':([^']+)'/g)].map(match => match[1])) {
    if (plugin === 'capacitor-android' || plugin === 'capacitor-cordova-android-plugins') continue
    assert.ok(generated.includes(`project(':${plugin}')`), `capacitor.build.gradle must consume ${plugin}`)
  }
})

test('every version variable used by Gradle is defined in android/variables.gradle', () => {
  const defined = new Set([...variables.matchAll(/^\s*(\w+)\s*=/gm)].map(match => match[1]))
  const used = new Set([...appGradle.matchAll(/\$(\w+Version|\w+AndroidVersion)/g)].map(match => match[1]))
  assert.ok(used.size >= 5, `expected the template variables, found ${used.size}`)
  const undefinedVariables = [...used].filter(name => !defined.has(name))
  assert.deepEqual(undefinedVariables, [], 'undefined Gradle version variables')
  // Naming consistency: the plugin-generated file and the app file agree.
  assert.match(appGradle, /namespace = "com\.fatorati\.app"/)
  assert.match(appGradle, /applicationId = "com\.fatorati\.app"/)
  assert.match(appGradle, /compileSdk = rootProject\.ext\.compileSdkVersion/)
  assert.match(appGradle, /minSdkVersion = rootProject\.ext\.minSdkVersion/)
  assert.match(appGradle, /targetSdkVersion = rootProject\.ext\.targetSdkVersion/)
})

test('the colours referenced by the app resources are actually provided', () => {
  const appValues = ['android/app/src/main/res/values/styles.xml', 'android/app/src/main/res/values/ic_launcher_background.xml', 'android/app/src/main/res/values/strings.xml']
    .map(file => readFileSync(file, 'utf8'))
    .join('\n')
  const capacitorColors = readFileSync(require.resolve('@capacitor/android/capacitor/src/main/res/values/colors.xml'), 'utf8')
  const definedHere = new Set([...appValues.matchAll(/<color name="([^"]+)"/g)].map(match => match[1]))
  const definedByCapacitor = new Set([...capacitorColors.matchAll(/<color[^>]*name="([^"]+)"/g)].map(match => match[1]))
  const referenced = [...appValues.matchAll(/@color\/([A-Za-z0-9_]+)/g)].map(match => match[1])
  assert.ok(referenced.length >= 3, 'expected the theme to reference the template colours')
  for (const color of referenced) {
    if (definedHere.has(color)) continue
    assert.ok(definedByCapacitor.has(color), `@color/${color} is defined nowhere`)
    assert.ok(dependencyBlock.includes("project(':capacitor-android')"), `@color/${color} comes from :capacitor-android, which must stay a dependency`)
  }
})

test('the manifest, the Capacitor config and Gradle agree on the package', () => {
  const manifest = readFileSync('android/app/src/main/AndroidManifest.xml', 'utf8')
  const capacitorConfig = readFileSync('capacitor.config.ts', 'utf8')
  assert.match(capacitorConfig, /appId: 'com\.fatorati\.app'/)
  // AGP 8 rejects a package attribute in the manifest; the namespace lives in Gradle,
  // the components stay relative, and the FileProvider uses ${applicationId}.
  assert.equal(/\spackage="/.test(manifest), false, 'the manifest must not declare a package attribute')
  assert.match(manifest, /android:name="\.MainActivity"/)
  assert.match(manifest, /android:authorities="\$\{applicationId\}\.fileprovider"/)
  assert.match(manifest, /android\.permission\.POST_NOTIFICATIONS/)
  assert.match(manifest, /android\.permission\.USE_BIOMETRIC/)
  // Exact alarms must stay removed: the plugin declares them, the app deletes them.
  assert.match(manifest, /android\.permission\.SCHEDULE_EXACT_ALARM" tools:node="remove"/)
  assert.match(manifest, /android\.permission\.USE_EXACT_ALARM" tools:node="remove"/)
  assert.equal(/android\.permission\.INTERNET/.test(manifest), false)
  assert.match(manifest, /android:allowBackup="false"/)
  assert.match(manifest, /android:fullBackupContent="false"/)
  assert.match(manifest, /android:dataExtractionRules="@xml\/data_extraction_rules"/)
})

test('R8/ProGuard and Vite bundle obfuscation harden both native and WebView code', async () => {
  const gradleProperties = readFileSync('android/gradle.properties', 'utf8')
  const proguardRules = readFileSync('android/app/proguard-rules.pro', 'utf8')
  const viteConfig = readFileSync('vite.config.ts', 'utf8')

  // R8 full mode and resource optimizations must be enabled.
  assert.match(gradleProperties, /^android\.enableR8\.fullMode=true$/m)
  assert.match(gradleProperties, /^android\.enableResourceOptimizations=true$/m)

  // Both debug and release build types run R8 minification and resource shrinking,
  // and `.map` source maps are excluded from packaged assets.
  assert.match(appGradle, /ignoreAssetsPattern\s*=.*!\*\.map/)
  assert.match(appGradle, /debug\s*\{[\s\S]*?minifyEnabled\s+true[\s\S]*?shrinkResources\s+true/)
  assert.match(appGradle, /release\s*\{[\s\S]*?minifyEnabled\s+true[\s\S]*?shrinkResources\s+true[\s\S]*?debugSymbolLevel\s+'NONE'/)

  // ProGuard/R8 rules repackage obfuscated classes, rename SourceFile, strip Log calls,
  // and keep only plugin constructors and annotated bridge/callback methods (never `{ *; }`).
  assert.match(proguardRules, /-repackageclasses\s+'o'/)
  assert.match(proguardRules, /-allowaccessmodification/)
  assert.match(proguardRules, /-overloadaggressively/)
  assert.match(proguardRules, /-renamesourcefileattribute\s+SourceFile/)
  assert.match(proguardRules, /-assumenosideeffects\s+class\s+android\.util\.Log/)
  assert.match(proguardRules, /@com\.getcapacitor\.annotation\.ActivityCallback\s+<methods>;/)
  assert.match(proguardRules, /@com\.getcapacitor\.annotation\.PermissionCallback\s+<methods>;/)
  assert.equal(/-keep\s+@com\.getcapacitor\.annotation\.CapacitorPlugin\s+class\s+\*\s*\{\s*\*;\s*\}/.test(proguardRules), false)

  // Vite production build disables sourcemaps, hashes chunk/asset names, and runs
  // the AST string/constant obfuscator without introducing eval().
  assert.match(viteConfig, /sourcemap:\s*false/)
  assert.match(viteConfig, /entryFileNames:\s*'assets\/c-\[hash\]\.js'/)
  assert.match(viteConfig, /chunkFileNames:\s*'assets\/c-\[hash\]\.js'/)
  assert.match(viteConfig, /assetFileNames:\s*'assets\/a-\[hash\]\[extname\]'/)
  assert.match(viteConfig, /fatorati-obfuscate-bundle/)

  // Native MainActivity and Capacitor config lock out WebView debugging and bridge logging,
  // and encode SharedPreferences identifiers instead of leaving plain-text string literals.
  const mainActivity = readFileSync('android/app/src/main/java/com/fatorati/app/MainActivity.java', 'utf8')
  const screenSecurity = readFileSync('android/app/src/main/java/com/fatorati/app/ScreenSecurityPlugin.java', 'utf8')
  const capacitorConfig = readFileSync('capacitor.config.ts', 'utf8')
  assert.match(mainActivity, /WebView\.setWebContentsDebuggingEnabled\(false\)/)
  assert.equal(mainActivity.includes('"FatoratiSecurity"'), false)
  assert.equal(screenSecurity.includes('"FatoratiSecurity"'), false)
  assert.match(capacitorConfig, /webContentsDebuggingEnabled:\s*false/)
  assert.match(capacitorConfig, /loggingBehavior:\s*'none'/)
})
