// Run against the production bundle, not an Android emulator. See README.
import {chromium as playwright} from 'playwright'
import fs from 'node:fs/promises'
import assert from 'node:assert/strict'
await fs.mkdir('.tmp-ui',{recursive:true})
{
const dictionaries={};for(const lang of ['en','ar','fr','es','pt'])dictionaries[lang]=JSON.parse(await fs.readFile(`${process.cwd()}/src/i18n/${lang}.json`))
const browser=await playwright.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||undefined,args:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH?['--no-sandbox','--no-zygote','--single-process']:[],headless:true})
const errors=[],context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage()
page.on('pageerror',e=>errors.push(e.message));page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text())});page.on('dialog',dialog=>dialog.accept())
const nav=async(name)=>page.getByRole('button',{name:new RegExp(name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'$')}).last().click()
await page.goto(process.env.FATORATI_TEST_URL||'http://127.0.0.1:5173')
await page.getByLabel('6-digit PIN',{exact:true}).fill('123456');await page.getByLabel('Confirm PIN',{exact:true}).fill('123456');await page.getByRole('button',{name:'Create PIN',exact:true}).click()
await page.getByPlaceholder('Acme Inc.',{exact:true}).fill('Café أحمد')
await page.getByPlaceholder('John Doe',{exact:true}).fill('Owner')
await page.getByLabel('Currency',{exact:true}).selectOption('JPY')
await page.getByRole('button',{name:'Continue to Dashboard'}).click()
await page.getByRole('heading',{name:'Dashboard',exact:true}).first().waitFor()
await nav('Settings')
await page.getByLabel('Theme',{exact:true}).selectOption('dark')
await page.getByLabel('Time format',{exact:true}).selectOption('12h')
assert.equal(await page.locator('html').getAttribute('data-theme'),'dark')
let previous='en'
for(const lang of ['en','ar','fr','es','pt']){
 await page.getByLabel(dictionaries[previous].Language,{exact:true}).selectOption(lang)
 await page.waitForTimeout(150)
 assert.equal(await page.locator('html').getAttribute('lang'),lang)
 assert.equal(await page.locator('html').getAttribute('dir'),lang==='ar'?'rtl':'ltr')
 await page.screenshot({path:`.tmp-ui/settings-${lang}.png`,fullPage:true})
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`overflow ${lang}`)
 previous=lang
}
await page.getByLabel(dictionaries.pt.Language,{exact:true}).selectOption('en')
// Make an expense with 0 decimal currency and then 3 decimal currency.
await nav('Expenses');await page.getByRole('button',{name:'Add Expense',exact:true}).click()
await page.getByPlaceholder('Description *',{exact:true}).fill('JPY test')
await page.getByPlaceholder('Amount *',{exact:true}).fill('12.8')
await page.getByLabel('Currency',{exact:true}).selectOption('JPY')
await page.getByRole('button',{name:'Save',exact:true}).click()
await page.getByText('JPY test',{exact:true}).waitFor()
assert.match(await page.locator('main').innerText(),/13/)
await page.getByRole('button',{name:'Add Expense',exact:true}).click()
await page.getByPlaceholder('Description *',{exact:true}).fill('KWD test')
await page.getByPlaceholder('Amount *',{exact:true}).fill('1.2345')
await page.getByLabel('Currency',{exact:true}).selectOption('KWD')
await page.getByRole('button',{name:'Save',exact:true}).click()
await page.getByText('KWD test',{exact:true}).waitFor()
assert.match(await page.locator('main').innerText(),/1\.235/)
for(const screen of ['Dashboard','Customers','Projects','Invoices','Estimates','Expenses','Products','Reports','Settings']){
 await nav(screen);await page.waitForTimeout(100)
 assert.equal(await page.locator('html').getAttribute('data-theme'),'dark')
 await page.screenshot({path:`.tmp-ui/dark-${screen}.png`,fullPage:true})
}
// Switch time modes, Arabic digits and inspect dashboard output.
await page.getByLabel('Time format',{exact:true}).selectOption('24h');await nav('Dashboard')
const display24=await page.locator('main').innerText();assert.ok(!/\b(AM|PM)\b/.test(display24))
await nav('Settings');await page.getByLabel('Time format',{exact:true}).selectOption('12h');await nav('Dashboard')
assert.match(await page.locator('main').innerText(),/\b(AM|PM)\b/)
await nav('Settings');await page.getByLabel('Number digits',{exact:true}).selectOption('arab');await nav('Expenses')
assert.match(await page.locator('main').innerText(),/[٠-٩]/)
// Lock before data renders on a reload and reject wrong PIN.
await page.reload();await page.getByRole('heading',{name:'Unlock Fatorati'}).waitFor()
assert.ok(!(await page.locator('body').innerText()).includes('Café أحمد'))
await page.getByLabel('6-digit PIN',{exact:true}).fill('000000');await page.getByRole('button',{name:'Unlock',exact:true}).click()
await page.getByRole('alert').filter({hasText:'Incorrect PIN'}).waitFor()
await page.getByLabel('6-digit PIN',{exact:true}).fill('123456');await page.getByRole('button',{name:'Unlock',exact:true}).click()
await nav('Settings');await page.getByLabel('Number digits',{exact:true}).selectOption('latn')
// Encrypted browser export for a second isolated install.
const pw=page.getByLabel('Backup password',{exact:true});await pw.fill('portable-secret')
await page.getByLabel('Confirm password',{exact:true}).fill('portable-secret')
const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export Backup .fatorati',exact:true}).click()
const download=await downloadPromise;await download.saveAs('.tmp-ui/transfer.fatorati')
assert.equal(JSON.parse(await fs.readFile('.tmp-ui/transfer.fatorati','utf8')).format,'fatorati-encrypted')
assert.deepEqual(errors,[])
console.log('UI checks passed through encrypted export; errors:',errors)
await browser.close()
}
{
const browser=await playwright.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||undefined,args:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH?['--no-sandbox','--no-zygote','--single-process']:[],headless:true})
const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),errors=[]
page.on('pageerror',e=>errors.push(e.message));page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text())})
await context.addInitScript(()=>{
 const original=HTMLCanvasElement.prototype.toDataURL
 HTMLCanvasElement.prototype.toDataURL=function(...args){const result=original.apply(this,args);if(this.width===1240)window.__pdfPreview=result;return result}
})
const nav=async(name)=>page.getByRole('button',{name:new RegExp(name+'$')}).last().click()
await page.goto(process.env.FATORATI_TEST_URL||'http://127.0.0.1:5173')
await page.getByLabel('6-digit PIN',{exact:true}).fill('654321');await page.getByLabel('Confirm PIN',{exact:true}).fill('654321');await page.getByRole('button',{name:'Create PIN',exact:true}).click()
await page.getByText('Moving phones? Import an existing backup',{exact:true}).click()
await page.getByLabel('Import mode',{exact:true}).selectOption('replace')
const choose=page.waitForEvent('filechooser');await page.getByRole('button',{name:'Import Backup',exact:true}).click()
const chooser=await choose
// Simulate the native file picker's background transition. The selected File must
// survive the React unmount; it must not decrypt until the new PIN unlocks again.
await page.evaluate(()=>{Object.defineProperty(document,'visibilityState',{value:'hidden',configurable:true});document.dispatchEvent(new Event('visibilitychange'))})
await page.getByRole('heading',{name:'Unlock Fatorati'}).waitFor()
await chooser.setFiles('.tmp-ui/transfer.fatorati')
await page.evaluate(()=>{Object.defineProperty(document,'visibilityState',{value:'visible',configurable:true});document.dispatchEvent(new Event('visibilitychange'))})
await page.getByLabel('6-digit PIN',{exact:true}).fill('654321');await page.getByRole('button',{name:'Unlock',exact:true}).click()
await page.getByRole('button',{name:'Decrypt & Import'}).waitFor()
await page.getByLabel('Backup password',{exact:true}).last().fill('wrong');await page.getByRole('button',{name:'Decrypt & Import'}).click()
await page.getByRole('status').filter({hasText:'Wrong password'}).waitFor()
await page.getByLabel('Backup password',{exact:true}).last().fill('portable-secret');await page.getByRole('button',{name:'Decrypt & Import'}).click()
await page.getByRole('button',{name:'Confirm',exact:true}).click()
await page.getByText('Import complete:',{exact:false}).waitFor()
await page.screenshot({path:'.tmp-ui/import-summary.png',fullPage:true})
await page.getByRole('button',{name:'OK',exact:true}).click()
await page.getByRole('heading',{name:'Unlock Fatorati'}).waitFor()
await page.getByLabel('6-digit PIN',{exact:true}).fill('654321');await page.getByRole('button',{name:'Unlock',exact:true}).click()
await nav('Expenses');await page.getByText('KWD test',{exact:true}).waitFor();assert.match(await page.locator('main').innerText(),/KWD\s1\.235/);assert.match(await page.locator('main').innerText(),/¥13/)
assert.equal(await page.locator('html').getAttribute('data-theme'),'dark')
await nav('Customers');await page.getByRole('button',{name:'Add Customer',exact:true}).click();await page.getByPlaceholder('Name *',{exact:true}).fill('Client عميل');await page.getByRole('button',{name:'Save',exact:true}).click()
await nav('Invoices');await page.getByRole('button',{name:'New Invoice',exact:true}).click()
await page.getByLabel('Currency',{exact:true}).selectOption('KWD')
await page.getByLabel('Language',{exact:true}).last().selectOption('ar')
await page.getByLabel('Customer',{exact:true}).selectOption({label:'Client عميل'})
await page.getByPlaceholder('Description',{exact:true}).fill('خدمة Café')
await page.getByPlaceholder('Quantity',{exact:true}).fill('2');await page.getByPlaceholder('Price',{exact:true}).fill('1.2345')
await page.getByRole('button',{name:'Create Invoice',exact:true}).click()
const download=page.waitForEvent('download');await page.getByTitle('Download PDF',{exact:true}).click();const pdf=await download;await pdf.saveAs('.tmp-ui/invoice-ar.pdf')
assert.equal((await fs.readFile('.tmp-ui/invoice-ar.pdf')).subarray(0,5).toString(),'%PDF-')
const preview=await page.evaluate(()=>window.__pdfPreview)
await fs.writeFile('.tmp-ui/invoice-ar-color.png',Buffer.from(preview.split(',')[1],'base64'))
await page.getByText('Document options',{exact:true}).click()
await page.getByLabel('Use color in PDFs',{exact:true}).click()
await page.waitForFunction(()=>document.querySelector('input[type=checkbox]')?.checked===false)
const monochrome=page.waitForEvent('download');await page.getByTitle('Download PDF',{exact:true}).click();await (await monochrome).saveAs('.tmp-ui/invoice-ar-bw.pdf')
const bw=await page.evaluate(()=>window.__pdfPreview)
await fs.writeFile('.tmp-ui/invoice-ar-bw.png',Buffer.from(bw.split(',')[1],'base64'))
assert.notEqual(preview,bw)
assert.deepEqual(errors,[])
console.log('SECOND INSTALL restored with a different PIN, picker survived simulated background, wrong password rejected, PDF exported; errors:',errors)
await browser.close()
}
